### ISSUE TITLE
Budget / set router & screen layout 

### ISSUE THREAD

**Issue by earlyoonj** [whalefox/expense-scheduler#1]
# Requirement
- Set screens: Budget - List, Form, Detail
- Set layout for screens

# Todos
## Router
- [x] Screens: Budget - List, Form, Detail

### BudgetList
- [x] BudgetItem
### BudgetDetail
- [x] Status: Carousel - Date, Total, Category
- [x] Amount: Chart - Doughnut, Bar
- [x] Transactions: List, Form, Detail
